export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const CLEAN_BREEDS = "CLEAN_BREEDS";
export const GET_CARDS_BREEDS = "GET_CARDS_BREEDS";
export const GET_BREED_ID = "GET_BREED_ID";
export const GET_BREEDS_FOR_PAGE = "GET_BREEDS_FOR_PAGE";
